# Generated by Django 4.0.6 on 2022-07-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_aluno_user_alter_enfermeiro_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('tratamento', models.TextField()),
                ('sintomas', models.TextField()),
                ('evitar', models.TextField()),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.enfermeiro')),
            ],
        ),
    ]
