# Generated by Django 4.0.6 on 2022-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
