# Generated by Django 4.0.6 on 2022-07-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_aluno_tel_responsavel_alter_aluno_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('assunto', models.TextField()),
                ('apresentadores', models.CharField(max_length=200)),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.enfermeiro')),
            ],
        ),
    ]
