# Generated by Django 4.0.6 on 2022-07-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='assunto',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='tema',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
